#!/bin/bash

# remastersys script to make an installable livecd/dvd from a Debian installed 
# and customized system
#
#
#  Created by Tony "Fragadelic" Brijeski
#
#  Copyright 2007,2008,2009,2010 Under the GNU GPL2 License
#
#  Originally Created February 12th, 2007
#
#  
#
#
#

# checking to make sure script is running with root privileges
. /etc/remaster/remaster.version

testroot="`whoami`"

if [ "$testroot" != "root" ]; then
     echo "Usage of remaster $REMASTERVERSION is as follows:"
     echo " "
     echo "   sudo remaster backup|clean|dist [cdfs|iso] [filename.iso]"
     echo " "
     echo " "
     echo "Examples:"
     echo " "
     echo "   sudo remaster backup   (to make a livecd/dvd backup of your system)"
     echo " "
     echo "   sudo remaster backup custom.iso"
     echo "                             (to make a livecd/dvd backup and call the iso custom.iso)" 
     echo " "
     echo "   sudo remaster clean    (to clean up temporary files of remaster)"
     echo " "
     echo "   sudo remaster dist     (to make a distributable livecd/dvd of your system)"
     echo " "
     echo "   sudo remaster dist cdfs"
     echo "                             (to make a distributable livecd/dvd filesystem only)"
     echo " "
     echo "   sudo remaster dist iso custom.iso"
     echo "                             (to make a distributable iso named custom.iso but only"
     echo "                              if the cdfs is already present)"
     echo " "
     echo "   cdfs and iso options should only be used if you wish to modify something on the"
     echo "   cd before the iso is created.  An example of this would be to modify the isolinux"
     echo "   portion of the livecd/dvd"
     echo " "

     exit 1
fi

# load the remaster.conf file 

. /etc/remaster.conf

#Bug live config KDE
sed -i 's/rm/#rm/g' /lib/live/config/1060-kde-services

# if the remaster.conf file is incorrect or missing, make sure to set defaults

#if [ "$LIVEUSER" = "" ]; then
#Somebody must have removed the username from the configuration file
#echo 
#this is a custom live user
#LIVEUSER="custom"
#fi

#make sure live user is all lowercase
#LIVEUSER="`echo $LIVEUSER | awk '{print tolower ($0)}'`"


if [ "$WORKDIR" = "" ]; then
    WORKDIR="/home/remaster"
else
    WORKDIR="$WORKDIR"
fi

#if [ "$LIVECDLABEL" = "" ]; then
#LIVECDLABEL=$LIVECDLABEL
#fi

if [ "$CDBOOTTYPE" != "GRUB" ]; then
CDBOOTTYPE="ISOLINUX"
fi

if [ "$2" = "cdfs" ]; then
echo "Creating the cd filesystem only"
elif [ "$2" = "iso" ]; then
echo "Creating the iso file only"
elif [ "$2" = "" ]; then
echo " "
else
CUSTOMISO="$2"
fi

if [ "$3" != "" ]; then
CUSTOMISO="$3"
fi

if [ "$CUSTOMISO" = "" ]; then
CUSTOMISO=""
fi

case $1  in

  backup)
     echo "System Backup Mode Selected"
     ;;

  clean)
     echo "Removing the build directory now..."
     rm -rf $WORKDIR
     echo "Done...Exiting"
     exit 0
     ;;

  dist)
     echo "Distribution Mode Selected"
     ;;



  *)
     echo "Usage of remaster $REMASTERVERSION is as follows:"
     echo " "
     echo "   sudo remaster backup|clean|dist [cdfs|iso] [filename.iso]"
     echo " "
     echo " "
     echo "Examples:"
     echo " "
     echo "   sudo remaster backup   (to make a livecd/dvd backup of your system)"
     echo " "
     echo "   sudo remaster backup custom.iso"
     echo "                             (to make a livecd/dvd backup and call the iso custom.iso)" 
     echo " "
     echo "   sudo remaster clean    (to clean up temporary files of remaster)"
     echo " "
     echo "   sudo remaster dist     (to make a distributable livecd/dvd of your system)"
     echo " "
     echo "   sudo remaster dist cdfs"
     echo "                             (to make a distributable livecd/dvd filesystem only)"
     echo " "
     echo "   sudo remaster dist iso custom.iso"
     echo "                             (to make a distributable iso named custom.iso but only"
     echo "                              if the cdfs is already present)"
     echo " "
     echo "   cdfs and iso options should only be used if you wish to modify something on the"
     echo "   cd before the iso is created.  An example of this would be to modify the isolinux"
     echo "   portion of the livecd/dvd"
     echo " "
     exit 1
     ;;

esac


cdfs (){

# Step 3 - Create the CD tree in $WORKDIR/ISOTMP
echo "Checking if the $WORKDIR folder has been created"
if [ -d "$WORKDIR" ]; then
rm -rf $WORKDIR/dummysys/var/*
rm -rf $WORKDIR/dummysys/etc/*
else
mkdir -p $WORKDIR/ISOTMP/boot
mkdir -p $WORKDIR/ISOTMP/efi
mkdir -p $WORKDIR/ISOTMP/live
mkdir -p $WORKDIR/ISOTMP/isolinux
mkdir -p $WORKDIR/ISOTMP/install
mkdir -p $WORKDIR/ISOTMP/preseed
mkdir -p $WORKDIR/ISOTMP/pool
mkdir -p $WORKDIR/dummysys/dev
mkdir -p $WORKDIR/dummysys/etc/live
mkdir -p $WORKDIR/dummysys/proc
mkdir -p $WORKDIR/dummysys/tmp
mkdir -p $WORKDIR/dummysys/sys
mkdir -p $WORKDIR/dummysys/mnt
mkdir -p $WORKDIR/dummysys/media/cdrom
mkdir -p $WORKDIR/dummysys/var
mkdir -p $WORKDIR/dummysys/etc/skel/Desktop
cp /usr/share/applications/remaster-install.desktop $WORKDIR/dummysys/etc/skel/Desktop
cp /usr/share/applications/Remaster-Grub-Restore.desktop $WORKDIR/dummysys/etc/skel/Desktop
chmod +x $WORKDIR/dummysys/etc/skel/Desktop/Remaster-Grub-Restore.desktop
chmod +x $WORKDIR/dummysys/etc/skel/Desktop/remaster-install.desktop
cp /etc/remaster/skel/.bash_profile $WORKDIR/dummysys/etc/skel
chmod ug+rwx,o+rwt $WORKDIR/dummysys/tmp

fi




echo "Copying /var and /etc to temp area and excluding extra files"

if [ "$EXCLUDES" != "" ]; then
for addvar in $EXCLUDES ; do
VAREXCLUDES="$VAREXCLUDES --exclude='$addvar' "
done
fi

# if this is kde, copy the adept_notifier_auto.desktop to /etc/remaster so the installer can put it back as live-initramfs removes it altogether
if [ -f /usr/share/autostart/adept_notifier_auto.desktop ]; then
cp /usr/share/autostart/adept_notifier_auto.desktop /etc/remaster/
fi

# copy trackerd stuff as live-initramfs disables it
if [ -f /etc/xdg/autostart/tracker-applet.desktop ]; then
cp /etc/xdg/autostart/tracker-applet.desktop /etc/remaster
fi
if [ -f /etc/xdg/autostart/trackerd.desktop ]; then
cp /etc/xdg/autostart/trackerd.desktop.xdg /etc/remaster
fi
if [ -f /usr/share/autostart/trackerd.desktop ]; then
cp /usr/share/autostart/trackerd.desktop.share /etc/remaster
fi



rsync --exclude='*.log.*' --exclude='*.pid' --exclude='*.bak' --exclude='*.[0-9].gz' --exclude='*.deb' $VAREXCLUDES-a /var/. $WORKDIR/dummysys/var/.
rsync $VAREXCLUDES-a /etc/. $WORKDIR/dummysys/etc/.

rm -rf $WORKDIR/dummysys/etc/X11/xorg.conf*
rm -rf $WORKDIR/dummysys/etc/resolv.conf
rm -rf $WORKDIR/dummysys/etc/hosts
rm -rf $WORKDIR/dummysys/etc/hostname
#rm -rf $WORKDIR/dummysys/etc/timezone
rm -rf $WORKDIR/dummysys/etc/mtab
rm -rf $WORKDIR/dummysys/etc/fstab
rm -rf $WORKDIR/dummysys/etc/udev/rules.d/70-persistent*
rm -rf $WORKDIR/dummysys/etc/cups/ssl/server.crt
rm -rf $WORKDIR/dummysys/etc/cups/ssl/server.key
rm -rf $WORKDIR/dummysys/etc/ssh/ssh_host_rsa_key
rm -rf $WORKDIR/dummysys/etc/ssh/ssh_host_dsa_key.pub
rm -rf $WORKDIR/dummysys/etc/ssh/ssh_host_dsa_key
rm -rf $WORKDIR/dummysys/etc/ssh/ssh_host_rsa_key.pub
#ls $WORKDIR/dummysys/var/lib/apt/lists | grep -v ".gpg" | grep -v "lock" | grep -v "partial" | xargs -i rm $WORKDIR/dummysys/var/lib/apt/lists/{} ; 
    find $WORKDIR/dummysys/var/log $WORKDIR/dummysys/var/lock $WORKDIR/dummysys/var/backups $WORKDIR/dummysys/var/tmp -type f -exec rm {} \; &> /dev/null
if [ "$1" = "dist" ]; then


#Bug MDM mint linux
    rm -rf $WORKDIR/dummysys/etc/mdm/mdm.conf
    echo [daemon] >> $WORKDIR/dummysys/etc/mdm/mdm.conf
    echo AutomaticLoginEnable=true >> $WORKDIR/dummysys/etc/mdm/mdm.conf
    echo AutomaticLogin=$LIVEUSER >> $WORKDIR/dummysys/etc/mdm/mdm.conf
#lightdm
    echo autologin-user-timeout=0 >> $WORKDIR/dummysys/etc/lightdm/lightdm.conf
    echo autologin-user=$LIVEUSER >> $WORKDIR/dummysys/etc/lightdm/lightdm.conf
#kdm debian 
    sed -i 's/AutoLoginEnable/#AutoLoginEnable/g' $WORKDIR/dummysys/etc/kde4/kdm/kdmrc
    sed -i 's/AutoLoginUser/#AutoLoginUser/g' $WORKDIR/dummysys/etc/kde4/kdm/kdmrc   
    echo AutoLoginEnable=true >> $WORKDIR/dummysys/etc/kde4/kdm/kdmrc
    echo AutoLoginUser=$LIVEUSER >> $WORKDIR/dummysys/etc/kde4/kdm/kdmrc
#sddm debian 
    sed -i 's/Session=/Session=plasma.desktop/g' $WORKDIR/dummysys/etc/sddm.conf
    sed -i 's/User=/User=$LIVEUSER/g' $WORKDIR/dummysys/etc/sddm.conf 
#GDM3
    rm -rf $WORKDIR/dummysys/etc/gdm3/daemon.conf
    echo [daemon] >> $WORKDIR/dummysys/etc/gdm3/daemon.conf
    echo AutomaticLoginEnable=True >> $WORKDIR/dummysys/etc/gdm3/daemon.conf
    echo AutomaticLogin=$LIVEUSER >> $WORKDIR/dummysys/etc/gdm3/daemon.conf    

rm -rf $WORKDIR/dummysys/etc/group
rm -rf $WORKDIR/dummysys/etc/passwd
rm -rf $WORKDIR/dummysys/etc/shadow
rm -rf $WORKDIR/dummysys/etc/shadow-
rm -rf $WORKDIR/dummysys/etc/gshadow
rm -rf $WORKDIR/dummysys/etc/gshadow-


find $WORKDIR/dummysys/var/run $WORKDIR/dummysys/var/log $WORKDIR/dummysys/var/mail $WORKDIR/dummysys/var/spool $WORKDIR/dummysys/var/lock $WORKDIR/dummysys/var/backups $WORKDIR/dummysys/var/tmp -type f -exec rm {} \;

#fix for live scripts setup Contributed by AnthLee of SalineOS
rm -rf $WORKDIR/dummysys/var/lib/live/config/*

for i in dpkg.log lastlog mail.log syslog auth.log daemon.log faillog lpr.log mail.warn user.log boot debug mail.err messages wtmp bootstrap.log dmesg kern.log mail.info
do
        touch $WORKDIR/dummysys/var/log/${i}
done

# remove the non system users on the passwd and group files and copy them to dummysys

# see if any temp users left over from previous versions of remaster as the process has now changed

grep '^[^:]*:[^:]*:[5-9][0-9][0-9]:' /etc/passwd | awk -F ":" '{print "/usr/sbin/userdel -f",$1}'> $WORKDIR/cleantmpusers
. $WORKDIR/cleantmpusers

grep '^[^:]*:[^:]*:[0-9]:' /etc/passwd >> $WORKDIR/dummysys/etc/passwd
grep '^[^:]*:[^:]*:[0-9][0-9]:' /etc/passwd >> $WORKDIR/dummysys/etc/passwd
grep '^[^:]*:[^:]*:[0-9][0-9][0-9]:' /etc/passwd >> $WORKDIR/dummysys/etc/passwd
grep '^[^:]*:[^:]*:[3-9][0-9][0-9][0-9][0-9]:' /etc/passwd >> $WORKDIR/dummysys/etc/passwd

grep '^[^:]*:[^:]*:[0-9]:' /etc/group >> $WORKDIR/dummysys/etc/group
grep '^[^:]*:[^:]*:[0-9][0-9]:' /etc/group >> $WORKDIR/dummysys/etc/group
grep '^[^:]*:[^:]*:[0-9][0-9][0-9]:' /etc/group >> $WORKDIR/dummysys/etc/group
grep '^[^:]*:[^:]*:[3-9][0-9][0-9][0-9][0-9]:' /etc/group >> $WORKDIR/dummysys/etc/group

grep '^[^:]*:[^:]*:[5-9][0-9][0-9]:' /etc/passwd | awk -F ":" '{print $1}'> $WORKDIR/tmpusers1
grep '^[^:]*:[^:]*:[1-9][0-9][0-9][0-9]:' /etc/passwd | awk -F ":" '{print $1}'> $WORKDIR/tmpusers2
grep '^[^:]*:[^:]*:[1-2][0-9][0-9][0-9][0-9]:' /etc/passwd | awk -F ":" '{print $1}'> $WORKDIR/tmpusers3

cat $WORKDIR/tmpusers1 $WORKDIR/tmpusers2 $WORKDIR/tmpusers3 > $WORKDIR/tmpusers

cat $WORKDIR/tmpusers | while read LINE ;do

echo $LINE | xargs -i sed -e 's/,{}//g' $WORKDIR/dummysys/etc/group > $WORKDIR/dummysys/etc/group.new1
echo $LINE | xargs -i sed -e 's/{},//g' $WORKDIR/dummysys/etc/group.new1 > $WORKDIR/dummysys/etc/group.new2
echo $LINE | xargs -i sed -e 's/{}//g' $WORKDIR/dummysys/etc/group.new2 > $WORKDIR/dummysys/etc/group

rm -rf $WORKDIR/dummysys/etc/group.new1 $WORKDIR/dummysys/etc/group.new2

done

fi

# make sure the adduser and autologin functions of casper as set according to the mode

#[ "$1" = "dist" ] && [ ! -d $WORKDIR/dummysys/home ] && mkdir $WORKDIR/dummysys/home
#[ "$1" = "dist" ] && chmod 755 /usr/share/initramfs-tools/scripts/live-bottom/*adduser /usr/share/initramfs-tools/scripts/live-bottom/*autologin 
#[ "$1" = "backup" ] && [ -d $WORKDIR/dummysys/home ] && rm -rf $WORKDIR/dummysys/home
#[ "$1" = "backup" ] && chmod 644 /usr/share/initramfs-tools/scripts/live-bottom/*adduser /usr/share/initramfs-tools/scripts/live-bottom/*autologin


# copy over some of the necessary stuff for the livecd

if [ -f /etc/remaster/preseed/*.seed ]; then
cp /etc/remaster/preseed/* $WORKDIR/ISOTMP/preseed/
cp -fr /etc/remaster/efi/* $WORKDIR/ISOTMP/efi/
cp -fr /etc/remaster/boot/* $WORKDIR/ISOTMP/boot/
cp -fr /etc/remaster/grub.ucf-dist $WORKDIR/ISOTMP/
fi


#check if system has UEFI and Installer data to move over by Wallion Alves
if [ -d /etc/remaster/data ]; then
log_msg "Moving all data files to the ISOTMP folder"
cp -a /etc/remaster/data/* $WORKDIR/ISOTMP/
else
log_msg "No data folder found"	
fi

#cp $WORKDIR/ISOTMP/efi/boot/bootx64.efi $WORKDIR/ISOTMP/efi/boot/fallback.efi
sed -i "s/__LIVECDLABEL__/$LIVECDLABEL/g" $WORKDIR/ISOTMP/boot/grub/grub.cfg



if [ -f /etc/remaster/preseed/*.seed ]; then
cp /etc/remaster/preseed/* $WORKDIR/ISOTMP/preseed/
fi


#BOOT Type selected is GRUB
if [ "$ISOBOOT" = "GRUB" ]; then

cp /etc/remaster/isolinux/memtest.bin $WORKDIR/ISOTMP/memtest.bin

mkdir -p $WORKDIR/ISOTMP/boot/grub
mkdir -p $WORKDIR/ISOTMP/usr/share/grub
cp -a /boot/grub/* $WORKDIR/ISOTMP/boot/grub/
cp -a /usr/share/grub/* $WORKDIR/ISOTMP/usr/share/grub/
cp /etc/remaster/grub/grub.cfg $WORKDIR/ISOTMP/boot/grub/grub.cfg
cp /etc/remaster/grub.png $WORKDIR/ISOTMP/boot/grub/grub.png

sed -i -e 's/__LIVECDLABEL__/'"$LIVECDLABEL"'/g' $WORKDIR/ISOTMP/boot/grub/grub.cfg

if [ ! -d /etc/plymouth ]; then

sed -i -e 's/splash//g' $WORKDIR/ISOTMP/boot/grub/grub.cfg

fi



else
#BOOT Type selected is ISOLINUX

mkdir -p $WORKDIR/ISOTMP/isolinux

if [ `ls /etc/remaster/customisolinux` ]; then

cp /etc/remaster/customisolinux/* $WORKDIR/ISOTMP/isolinux/

else

cp /etc/remaster/isolinux/* $WORKDIR/ISOTMP/isolinux/

sed -i -e 's/__LIVECDLABEL__/'"$LIVECDLABEL"'/g' $WORKDIR/ISOTMP/isolinux/menu.cfg

if [ ! -d /etc/plymouth ]; then

sed -i -e 's/splash//g' $WORKDIR/ISOTMP/isolinux/live.cfg

fi

fi

fi

sleep 1



# Step 4 - Prepare live.conf depending on whether this is a backup or dist

if [ "$1" = "backup" ]; then
LIVEUSER="`grep '^[^:]*:[^:]*:1000:' /etc/passwd | awk -F ":" '{ print $1 }'`"

#fix Thunar volmanrc for live
for i in `ls /home/*`; do

if [ /home/$i/.config/Thunar/volmanrc ]; then
  sed -i -e 's/TRUE/FALSE/g' /home/$i/.config/Thunar/volmanrc
  cp -f /home/$i/.config/volmanrc /root/.config/Thunar/volmanrc
fi

done

fi
if [ ! -d /etc/live ]; then
mkdir -p /etc/live
fi

echo "export LIVE_USERNAME=\"$LIVEUSER\"" > /etc/live/config.conf
echo "export LIVE_USER_FULLNAME=\"$LIVEUSER\"" >> /etc/live/config.conf
echo "export LIVE_HOSTNAME=\"$LIVEUSER\"" >> /etc/live/config.conf
echo "export LIVE_USER_DEFAULT_GROUPS=\"audio,cdrom,dialout,floppy,video,plugdev,netdev,powerdev,adm,sudo\"" >> /etc/live/config.conf
echo "export LIVE_LOCALES=\"pt_BR.UTF-8\"" >> /etc/live/config.conf
echo "export LIVE_TIMEZONE=\"America/Sao_Paulo\"" >> /etc/live/config.conf
echo "DISTRIBUTION_NAME= \"$LIVEUSER\"" > /etc/live-installer/install.conf
echo "LIVE_MEDIA_SOURCE = /lib/live/mount/medium/live/filesystem.squashfs" >> /etc/live-installer/install.conf
echo "LIVE_MEDIA_TYPE = squashfs" >> /etc/live-installer/install.conf
echo "LIVECDLABEL = \"$LIVECDLABEL\"" >> /etc/live-installer/install.conf
echo "LIVE_USER_NAME= \"$LIVEUSER\"" >> /etc/live-installer/install.conf
echo "LIVEUSER = \"$LIVEUSER\"" >> /etc/live-installer/install.conf
if [ "$1" = "backup" ]; then
echo "export LIVE_NOCONFIGS=\"002-user-setup,004-locales,005-tzdata,006-gdm,007-gdm3,008-kdm,009-lxdm,010-nodm,011-slim,015-keyboard-configuration,102-gnome-panel-data,103-gnome-power-manager,104-gnome-screensaver,107-kde-services,116-login\"" >> /etc/live/config.conf
fi



cp /etc/live/config.conf $WORKDIR/dummysys/etc/live/
sed -i 's/"//g' /etc/live-installer/install.conf
cp /etc/live-installer/install.conf $WORKDIR/dummysys/etc/live-installer/

sleep 1

echo "Setting up live options for $1 mode"

# make a new initial ramdisk including the live scripts
update-initramfs -t -c -k $(uname -r)

echo "Copying your kernel and initrd for the livecd"
cp /boot/vmlinuz-$(uname -r) $WORKDIR/ISOTMP/live/vmlinuz
cp /boot/initrd.img-$(uname -r) $WORKDIR/ISOTMP/live/initrd.img
cp /boot/vmlinuz-$(uname -r) $WORKDIR/ISOTMP/install/vmlinuz
cp /boot/initrd.img-$(uname -r) $WORKDIR/ISOTMP/install/initrd.gz

# Step 5 - Make filesystem.squashfs

if [ -f $WORKDIR/remaster.log ]; then
rm -f $WORKDIR/remaster.log
touch $WORKDIR/remaster.log
fi


if [ -f $WORKDIR/ISOTMP/live/filesystem.squashfs ]; then
rm -f $WORKDIR/ISOTMP/live/filesystem.squashfs
fi

echo "Creating filesystem.squashfs   ... this will take a while so be patient"


SQUASHFSOPTSHIGH="-no-recovery -always-use-fragments -b 1M"


echo "Adding stage 1 files/folders that the livecd requires."

# add the blank folders and trimmed down /var to the cd filesystem

mksquashfs $WORKDIR/dummysys/ $WORKDIR/ISOTMP/live/filesystem.squashfs -no-duplicates -comp xz $SQUASHFSOPTSHIGH 2>>$WORKDIR/remaster.log

sleep 1

echo "Adding stage 2 files/folders that the livecd requires."

# add the rest of the system depending on the mode selected

if [ "$1" = "backup" ]; then
mksquashfs / $WORKDIR/ISOTMP/live/filesystem.squashfs -no-duplicates $SQUASHFSOPTSHIGH -e \
.thumbnails \
.cache \
.bash_history \
Cache \
boot/grub \
dev \
etc \
media \
mnt \
proc \
sys \
tmp \
var \
$WORKDIR $EXCLUDES 2>>$WORKDIR/remaster.log
#return Thunar volmanrc back to normal
for i in `ls /home/*`; do

if [ /home/$i/.config/Thunar/volmanrc ]; then
  sed -i -e 's/FALSE/TRUE/g' /home/$i/.config/Thunar/volmanrc
  cp -f /home/$i/.config/volmanrc /root/.config/Thunar/volmanrc
fi

done

else
mksquashfs / $WORKDIR/ISOTMP/live/filesystem.squashfs -no-duplicates $SQUASHFSOPTSHIGH -e \
.thumbnails \
.cache \
.bash_history \
Cache \
boot/grub \
dev \
etc \
home \
media \
mnt \
proc \
sys \
tmp \
var \
$WORKDIR $EXCLUDES 2>>$WORKDIR/remaster.log

fi

sleep 1


#add some stuff the log in case of problems so I can troubleshoot it easier
echo "------------------------------------------------------" >>$WORKDIR/remaster.log
echo "Mount information" >>$WORKDIR/remaster.log
mount >>$WORKDIR/remaster.log
echo "------------------------------------------------------" >>$WORKDIR/remaster.log
echo "df information" >>$WORKDIR/remaster.log
df -h >>$WORKDIR/remaster.log
echo "------------------------------------------------------" >>$WORKDIR/remaster.log
echo "/etc/remaster.conf info" >>$WORKDIR/remaster.log
cat /etc/remaster.conf >>$WORKDIR/remaster.log
echo "------------------------------------------------------" >>$WORKDIR/remaster.log
echo "/etc/live/config.conf info" >>$WORKDIR/remaster.log
cat /etc/live/config.conf >>$WORKDIR/remaster.log
echo "------------------------------------------------------" >>$WORKDIR/remaster.log
echo "/etc/passwd info" >>$WORKDIR/remaster.log
cat $WORKDIR/dummysys/etc/passwd >>$WORKDIR/remaster.log
echo "------------------------------------------------------" >>$WORKDIR/remaster.log
echo "/etc/group info" >>$WORKDIR/remaster.log
cat $WORKDIR/dummysys/etc/group >>$WORKDIR/remaster.log
echo "------------------------------------------------------" >>$WORKDIR/remaster.log
echo "Command-line options = $@" >>$WORKDIR/remaster.log
echo "------------------------------------------------------" >>$WORKDIR/remaster.log


sleep 1

#checking the size of the compressed filesystem to ensure it meets the iso9660 spec for a single file" 
SQUASHFSSIZE=`ls -s $WORKDIR/ISOTMP/live/filesystem.squashfs | awk -F " " '{print $1}'`
if [ "$SQUASHFSSIZE" -gt "3999999" ]; then
echo " The compressed filesystem is larger than the iso9660 specification allows for a single file. You must try to reduce the amount of data you are backing up and try again."
echo " The compressed filesystem is larger than the iso9660 specification allows for a single file. You must try to reduce the amount of data you are backing up and try again.">>$WORKDIR/remaster.log

exit 1
fi


}

iso (){

CREATEISO="`which mkisofs`"
if [ "$CREATEISO" = "" ]; then
CREATEISO="`which xorriso`"
fi

# check to see if the cd filesystem exists

if [ ! -f "$WORKDIR/ISOTMP/live/filesystem.squashfs" ]; then
echo "The cd filesystem is missing.  Either there was a problem creating the compressed filesystem or you are trying to run sudo remaster dist iso before sudo remaster dist cdfs"
echo "The cd filesystem is missing.  Either there was a problem creating the compressed filesystem or you are trying to run sudo remaster dist iso before sudo remaster dist cdfs" >>$WORKDIR/remaster.log

exit 1
fi

#checking the size of the compressed filesystem to ensure it meets the iso9660 spec for a single file" 
SQUASHFSSIZE=`ls -s $WORKDIR/ISOTMP/live/filesystem.squashfs | awk -F " " '{print $1}'`
if [ "$SQUASHFSSIZE" -gt "3999999" ]; then
echo " The compressed filesystem is larger than the iso9660 specification allows for a single file. You must try to reduce the amount of data you are backing up and try again."
echo " The compressed filesystem is larger than the iso9660 specification allows for a single file. You must try to reduce the amount of data you are backing up and try again.">>$WORKDIR/remaster.log

exit 1
fi



#isolinux mode

sleep 1

# Step 6 - Make the ISO file

if [ "$ISOBOOT" = "GRUB" ]; then

echo "Creating $CUSTOMISO in $WORKDIR using grub-mkrescue"
echo "Creating $CUSTOMISO in $WORKDIR using grub-mkrescue" >>$WORKDIR/remaster.log
grub-mkrescue -o $WORKDIR/$CUSTOMISO $WORKDIR/ISOTMP/ 2>>$WORKDIR/remaster.log 1>>$WORKDIR/remaster.log


else
echo "Creating $CUSTOMISO in $WORKDIR using $CREATEISO"
echo "Creating $CUSTOMISO in $WORKDIR using $CREATEISO" >>$WORKDIR/remaster.log
$CREATEISO -as mkisofs -r -N -D -J -allow-leading-dots -V "$LIVECDLABEL" -cache-inodes -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -eltorito-alt-boot -e boot/grub/efi.img -no-emul-boot -o $WORKDIR/$CUSTOMISO "$WORKDIR/ISOTMP" 2>>$WORKDIR/remaster.log 1>>$WORKDIR/remaster.log

# create hybrid iso so it can be dd installed to a usb flash drive

echo "Making the iso into a hybrid image so it can be imaged to a usb key or burned to optical media"

isohybrid --uefi $WORKDIR/$CUSTOMISO
fi

dumpet -i $WORKDIR/*.iso

# create the md5 sum file so the user doesn't have to - this is good so the iso file can later be tested to ensure it hasn't become corrupted


echo "Creating $CUSTOMISO.md5 in $WORKDIR"
echo "Creating $CUSTOMISO.md5 in $WORKDIR" >>$WORKDIR/remaster.log

cd $WORKDIR
md5sum $CUSTOMISO > $CUSTOMISO.md5

sleep 1


echo "$WORKDIR/$CUSTOMISO is ready to be burned or tested in a virtual machine."
echo " "
echo "Check the size and if it is larger than 700MB you will need to burn it to a dvd"
echo " "
ls -hs $WORKDIR/$CUSTOMISO
ls -hs $WORKDIR/$CUSTOMISO >> $WORKDIR/remaster.log
echo " " 
echo "It is recommended to run 'sudo remaster clean' once you have burned and tested the $CUSTOMISO"
echo " "


}

# check to see if either iso or cdfs options have been invoked and proceed accordingly

if [ "$2" = "iso" ]; then
iso $@
elif [ "$2" = "cdfs" ]; then
cdfs $@
else
cdfs $@
iso $@
fi




exit 0